### ISSUE TITLE
LIKE button doesn't work?

### ISSUE THREAD

**Issue by bhatara007** [Jomsaruj/DEK-COM#63]
After I try to created the example post in your website, when I clicked the link button it's doesn't not show any action. I think you if your post has like button you need to show the number of total like for each post?

**Comment by patiphan2000** [comment]
Like button it use to give a coin to author of that blog, We apologize for not having any feedback to show is it work or not.
Now it was remove and replace with heart-shape button to indicate like,
You can check it out at [our website](https://www.dek-com.co).
Thanks for your feedback!!
