### ISSUE TITLE
Blank tag problem in the main blog post.

### ISSUE THREAD

**Issue by Noboomta** [Jomsaruj/DEK-COM#67]
### Suggestion and experience on the product

> Since I did use your product and looking to use this in the future, I have experienced a few issue on the product.

### 1. Cannot delete the blank tag.

> in /blog/create-blog/post
> The users cannot delete the blank tag when they are preparing to post (post page).

![image](https://user-images.githubusercontent.com/53256241/100536729-115f4f80-3255-11eb-84b8-376d96c6f0a2.png)

### 2. Styling(this is about the style, please think about this is **only** my suggestion.)

1. > Floating text on the blog type element. (I would be nice if you put the text to the middle of the blog)
![image](https://user-images.githubusercontent.com/53256241/100536449-3226a580-3253-11eb-85ed-16ce123ad142.png)
2. > It would be nice if the length of the display tag is the same as the length of the text.
![image](https://user-images.githubusercontent.com/53256241/100536485-7ade5e80-3253-11eb-87d7-80bc978d0e3c.png)

### 3. The link in the job opportunities sent to the yellow error page (View original link button).
![image](https://user-images.githubusercontent.com/53256241/100536632-7797a280-3254-11eb-8a1b-9087651eefd4.png)
![image](https://user-images.githubusercontent.com/53256241/100536659-9d24ac00-3254-11eb-831e-47c5a6fbc8c0.png)

**I like your cool popular tag show up, and the coloring while the mouse is on the post-topic and the green in the create post button. cheer up!**

**Comment by patiphan2000** [comment]
Empty tags bug is already fixed, Now you **cannot** create empty tag anymore.
Link in job opportunities is *automatically* redirect to the link that job owner put in if there are any error is most likely to be a user error.
You can check [our website](https://www.dek-com.co) to see all of the features.
Thank for your feedback!!
