### ISSUE TITLE
UI: some ui and information, not display

### ISSUE THREAD

**Issue by ZEZAY** [Jomsaruj/DEK-COM#73]
On the Profile page (both my own profile and other),
1. my skills not display
2. some data in my intro

URL: https://www.dek-com.co/Zaga/profile

![image](https://user-images.githubusercontent.com/44806732/101132923-68409c80-363a-11eb-9ece-15d04b556921.png)
![image](https://user-images.githubusercontent.com/44806732/101132930-6aa2f680-363a-11eb-8ee6-4525cbcb1109.png)

**Comment by patiphan2000** [comment]
It's work now!!
Thank for your feedback.
